package repository;

import model.Pokemon;
import java.util.ArrayList;
import java.util.List;

public class PokemonRepository {
    public static List<Pokemon> getAllPokemon() {
        List<Pokemon> pokemons = new ArrayList<>();

        pokemons.add(new Pokemon("Bulbasaur", "Grass", "Poison", 5, 49, 49, 65));
        pokemons.add(new Pokemon("Charmander", "Fire", null, 5, 52, 43, 50));
        pokemons.add(new Pokemon("Squirtle", "Water", null, 5, 48, 65, 50));
        pokemons.add(new Pokemon("Ivysaur", "Grass", "Poison", 16, 62, 63, 80));
        pokemons.add(new Pokemon("Venusaur", "Grass", "Poison", 32, 82, 83, 100));
        pokemons.add(new Pokemon("Charmeleon", "Fire", null, 16, 64, 58, 65));
        pokemons.add(new Pokemon("Charizard", "Fire", "Flying", 36, 84, 78, 85));
        pokemons.add(new Pokemon("Squirtle", "Water", null, 5, 48, 65, 50));
        pokemons.add(new Pokemon("Wartortle", "Water", null, 16, 63, 80, 65));
        pokemons.add(new Pokemon("Blastoise", "Water", null, 36, 83, 100, 85));
        pokemons.add(new Pokemon("Caterpie", "Bug", null, 3, 30, 35, 20));
        pokemons.add(new Pokemon("Metapod", "Bug", null, 7, 50, 55, 40));
        pokemons.add(new Pokemon("Butterfree", "Bug", "Flying", 10, 60, 50, 80));
        pokemons.add(new Pokemon("Weedle", "Bug", "Poison", 3, 35, 30, 20));
        pokemons.add(new Pokemon("Kakuna", "Bug", "Poison", 7, 45, 50, 35));
        pokemons.add(new Pokemon("Beedrill", "Bug", "Poison", 10, 65, 40, 45));
        pokemons.add(new Pokemon("Pidgey", "Normal", "Flying", 3, 40, 30, 35));
        pokemons.add(new Pokemon("Pidgeotto", "Normal", "Flying", 18, 63, 50, 60));
        pokemons.add(new Pokemon("Pidgeot", "Normal", "Flying", 36, 83, 60, 80));
        pokemons.add(new Pokemon("Rattata", "Normal", null, 3, 30, 56, 25));
        pokemons.add(new Pokemon("Raticate", "Normal", null, 20, 71, 60, 50));
        pokemons.add(new Pokemon("Spearow", "Normal", "Flying", 2, 45, 30, 30));
        pokemons.add(new Pokemon("Fearow", "Normal", "Flying", 20, 65, 60, 61));
        pokemons.add(new Pokemon("Ekans", "Poison", null, 3, 60, 44, 35));
        pokemons.add(new Pokemon("Arbok", "Poison", null, 22, 85, 69, 60));
        pokemons.add(new Pokemon("Pikachu", "Electric", null, 5, 55, 40, 35));
        pokemons.add(new Pokemon("Raichu", "Electric", null, 26, 90, 55, 50));
        pokemons.add(new Pokemon("Sandshrew", "Ground", null, 6, 50, 75, 35));
        pokemons.add(new Pokemon("Sandslash", "Ground", null, 22, 75, 100, 55));
        pokemons.add(new Pokemon("Nidoran♀", "Poison", null, 7, 47, 52, 40));
        pokemons.add(new Pokemon("Nidorina", "Poison", null, 16, 62, 67, 55));
        pokemons.add(new Pokemon("Nidoqueen", "Poison", "Ground", 30, 82, 87, 75));
        pokemons.add(new Pokemon("Nidoran♂", "Poison", null, 7, 56, 40, 35));
        pokemons.add(new Pokemon("Nidorino", "Poison", null, 16, 64, 57, 55));
        pokemons.add(new Pokemon("Nidoking", "Poison", "Ground", 36, 92, 77, 85));
        pokemons.add(new Pokemon("Clefairy", "Fairy", null, 6, 70, 48, 60));
        pokemons.add(new Pokemon("Clefable", "Fairy", null, 30, 95, 73, 90));
        pokemons.add(new Pokemon("Vulpix", "Fire", null, 6, 41, 40, 50));
        pokemons.add(new Pokemon("Ninetales", "Fire", null, 36, 76, 75, 100));
        pokemons.add(new Pokemon("Jigglypuff", "Normal", "Fairy", 6, 115, 45, 50));
        pokemons.add(new Pokemon("Wigglytuff", "Normal", "Fairy", 20, 140, 70, 85));
        pokemons.add(new Pokemon("Zubat", "Poison", "Flying", 3, 45, 35, 40));
        pokemons.add(new Pokemon("Golbat", "Poison", "Flying", 22, 75, 70, 75));
        pokemons.add(new Pokemon("Oddish", "Grass", "Poison", 5, 45, 50, 55));
        pokemons.add(new Pokemon("Gloom", "Grass", "Poison", 21, 60, 55, 65));
        pokemons.add(new Pokemon("Vileplume", "Grass", "Poison", 36, 75, 70, 85));
        pokemons.add(new Pokemon("Paras", "Bug", "Grass", 6, 35, 70, 55));
        pokemons.add(new Pokemon("Parasect", "Bug", "Grass", 24, 60, 80, 60));
        pokemons.add(new Pokemon("Venonat", "Bug", "Poison", 6, 60, 50, 40));
        pokemons.add(new Pokemon("Venomoth", "Bug", "Poison", 31, 65, 60, 90));
        pokemons.add(new Pokemon("Diglett", "Ground", null, 2, 55, 25, 15));
        pokemons.add(new Pokemon("Dugtrio", "Ground", null, 26, 80, 50, 35));
        pokemons.add(new Pokemon("Meowth", "Normal", null, 4, 45, 35, 45));
        pokemons.add(new Pokemon("Persian", "Normal", null, 28, 70, 60, 65));
        pokemons.add(new Pokemon("Psyduck", "Water", null, 4, 52, 48, 50));
        pokemons.add(new Pokemon("Golduck", "Water", null, 33, 80, 82, 75));
        pokemons.add(new Pokemon("Mankey", "Fighting", null, 5, 35, 35, 35));
        pokemons.add(new Pokemon("Primeape", "Fighting", null, 28, 65, 60, 65));
        pokemons.add(new Pokemon("Poliwag", "Water", null, 6, 40, 50, 40));
        pokemons.add(new Pokemon("Poliwhirl", "Water", null, 15, 65, 65, 50));
        pokemons.add(new Pokemon("Politoed", "Water", null, 30, 90, 75, 75));
        pokemons.add(new Pokemon("Machop", "Fighting", null, 5, 70, 35, 35));
        pokemons.add(new Pokemon("Machoke", "Fighting", null, 28, 80, 50, 35));
        pokemons.add(new Pokemon("Machamp", "Fighting", null, 42, 130, 80, 65));
        pokemons.add(new Pokemon("Bellsprout", "Grass", "Poison", 7, 40, 35, 50));
        pokemons.add(new Pokemon("Weepinbell", "Grass", "Poison", 21, 60, 50, 65));
        pokemons.add(new Pokemon("Victreebel", "Grass", "Poison", 36, 80, 65, 90));
        pokemons.add(new Pokemon("Tentacool", "Water", "Poison", 5, 40, 35, 40));
        pokemons.add(new Pokemon("Tentacruel", "Water", "Poison", 30, 80, 70, 65));
        pokemons.add(new Pokemon("Geodude", "Rock", "Ground", 4, 40, 100, 30));
        pokemons.add(new Pokemon("Graveler", "Rock", "Ground", 25, 55, 115, 45));
        pokemons.add(new Pokemon("Golem", "Rock", "Ground", 45, 85, 130, 55));
        pokemons.add(new Pokemon("Ponyta", "Fire", null, 7, 50, 40, 65));
        pokemons.add(new Pokemon("Rapidash", "Fire", null, 40, 80, 70, 105));
        pokemons.add(new Pokemon("Magnemite", "Electric", "Steel", 6, 35, 35, 70));
        pokemons.add(new Pokemon("Magneton", "Electric", "Steel", 30, 60, 60, 90));
        pokemons.add(new Pokemon("Farfetch'd", "Normal", "Flying", 5, 52, 55, 60));
        pokemons.add(new Pokemon("Doduo", "Normal", "Flying", 4, 45, 45, 35));
        pokemons.add(new Pokemon("Dodrio", "Normal", "Flying", 31, 60, 60, 60));
        pokemons.add(new Pokemon("Seel", "Water", null, 7, 65, 45, 50));
        pokemons.add(new Pokemon("Dewgong", "Water", "Ice", 34, 90, 70, 80));
        pokemons.add(new Pokemon("Grimer", "Poison", null, 6, 80, 50, 35));
        pokemons.add(new Pokemon("Muk", "Poison", null, 30, 105, 75, 65));
        pokemons.add(new Pokemon("Shellder", "Water", null, 6, 40, 35, 25));
        pokemons.add(new Pokemon("Cloyster", "Water", "Ice", 35, 50, 95, 85));
        pokemons.add(new Pokemon("Gastly", "Ghost", "Poison", 3, 35, 30, 35));
        pokemons.add(new Pokemon("Haunter", "Ghost", "Poison", 25, 50, 45, 50));
        pokemons.add(new Pokemon("Gengar", "Ghost", "Poison", 50, 65, 60, 60));
        pokemons.add(new Pokemon("Onix", "Rock", "Ground", 10, 35, 45, 30));
        pokemons.add(new Pokemon("Drowzee", "Psychic", null, 6, 48, 45, 43));
        pokemons.add(new Pokemon("Hypno", "Psychic", null, 31, 73, 70, 73));
        pokemons.add(new Pokemon("Krabby", "Water", null, 3, 30, 105, 25));
        pokemons.add(new Pokemon("Kingler", "Water", null, 28, 75, 115, 50));
        pokemons.add(new Pokemon("Exeggcute", "Grass", "Psychic", 6, 40, 35, 30));
        pokemons.add(new Pokemon("Exeggutor", "Grass", "Psychic", 30, 60, 95, 75));
        pokemons.add(new Pokemon("Cubone", "Ground", null, 6, 50, 95, 50));
        pokemons.add(new Pokemon("Marowak", "Ground", null, 28, 60, 110, 75));
        pokemons.add(new Pokemon("Hitmonlee", "Fighting", null, 20, 120, 53, 35));
        pokemons.add(new Pokemon("Hitmonchan", "Fighting", null, 20, 105, 79, 35));
        pokemons.add(new Pokemon("Lickitung", "Normal", null, 6, 35, 60, 35));
        pokemons.add(new Pokemon("Koffing", "Poison", null, 6, 65, 60, 35));
        pokemons.add(new Pokemon("Weezing", "Poison", null, 35, 90, 85, 60));
        pokemons.add(new Pokemon("Rhyhorn", "Rock", "Ground", 6, 80, 95, 30));
        pokemons.add(new Pokemon("Rhydon", "Rock", "Ground", 42, 105, 120, 45));
        pokemons.add(new Pokemon("Chansey", "Normal", null, 9, 5, 5, 250));
        pokemons.add(new Pokemon("Tangela", "Grass", null, 14, 65, 55, 70));
        pokemons.add(new Pokemon("Kangaskhan", "Normal", null, 25, 95, 80, 85));
        pokemons.add(new Pokemon("Horsea", "Water", null, 4, 30, 35, 30));
        pokemons.add(new Pokemon("Seadra", "Water", null, 36, 65, 55, 65));
        pokemons.add(new Pokemon("Goldeen", "Water", null, 6, 45, 40, 50));
        pokemons.add(new Pokemon("Seaking", "Water", null, 33, 65, 60, 70));
        pokemons.add(new Pokemon("Staryu", "Water", null, 5, 30, 45, 70));
        pokemons.add(new Pokemon("Starmie", "Water", "Psychic", 30, 60, 85, 115));
        pokemons.add(new Pokemon("Mr. Mime", "Psychic", "Fairy", 23, 45, 65, 100));
        pokemons.add(new Pokemon("Scyther", "Bug", "Flying", 20, 110, 80, 55));
        pokemons.add(new Pokemon("Jynx", "Ice", "Psychic", 24, 50, 35, 95));
        pokemons.add(new Pokemon("Electabuzz", "Electric", null, 30, 83, 57, 65));
        pokemons.add(new Pokemon("Magmar", "Fire", null, 30, 95, 57, 85));
        pokemons.add(new Pokemon("Pinsir", "Bug", null, 20, 125, 70, 55));
        pokemons.add(new Pokemon("Tauros", "Normal", null, 25, 100, 95, 75));
        pokemons.add(new Pokemon("Magikarp", "Water", null, 1, 10, 55, 20));
        pokemons.add(new Pokemon("Gyarados", "Water", "Flying", 20, 125, 79, 100));
        pokemons.add(new Pokemon("Lapras", "Water", "Ice", 15, 85, 80, 95));
        pokemons.add(new Pokemon("Ditto", "Normal", null, 5, 48, 48, 48));
        pokemons.add(new Pokemon("Eevee", "Normal", null, 5, 55, 50, 55));
        pokemons.add(new Pokemon("Vaporeon", "Water", null, 36, 130, 60, 95));
        pokemons.add(new Pokemon("Jolteon", "Electric", null, 36, 65, 60, 110));
        pokemons.add(new Pokemon("Flareon", "Fire", null, 36, 130, 60, 65));
        pokemons.add(new Pokemon("Espeon", "Psychic", null, 36, 65, 60, 110));
        pokemons.add(new Pokemon("Umbreon", "Dark", null, 36, 95, 65, 60));
        pokemons.add(new Pokemon("Leafeon", "Grass", null, 36, 130, 60, 65));
        pokemons.add(new Pokemon("Glaceon", "Ice", null, 36, 65, 60, 110));
        pokemons.add(new Pokemon("Sylveon", "Fairy", null, 36, 65, 65, 110));

        return pokemons;
    }
}